# Generated by Django 2.0.7 on 2018-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('precio_real', models.DecimalField(decimal_places=10, max_digits=20)),
                ('precio_estimado', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
